// Generated by scripts/embed-migrations.mjs from drizzle/. Do not edit.
export const migrations: { tag: string; statements: string[] }[] = [
  {
    "tag": "0000_init",
    "statements": [
      "CREATE TABLE `categories` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`slug` text NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`position` integer DEFAULT 0 NOT NULL\n);",
      "CREATE UNIQUE INDEX `categories_slug_unique` ON `categories` (`slug`);",
      "CREATE TABLE `editors` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`email` text NOT NULL,\n\t`name` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`bio` text DEFAULT '' NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`role` text DEFAULT 'editor' NOT NULL,\n\t`session_version` integer DEFAULT 1 NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL\n);",
      "CREATE UNIQUE INDEX `editors_email_unique` ON `editors` (`email`);",
      "CREATE UNIQUE INDEX `editors_slug_unique` ON `editors` (`slug`);",
      "CREATE TABLE `messages` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`email` text NOT NULL,\n\t`subject` text DEFAULT '' NOT NULL,\n\t`body` text NOT NULL,\n\t`ip_hash` text NOT NULL,\n\t`read` integer DEFAULT false NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL\n);",
      "CREATE INDEX `messages_ip` ON `messages` (`ip_hash`,`created_at`);",
      "CREATE TABLE `post_views` (\n\t`post_id` integer NOT NULL,\n\t`day` text NOT NULL,\n\t`count` integer DEFAULT 0 NOT NULL,\n\tPRIMARY KEY(`post_id`, `day`),\n\tFOREIGN KEY (`post_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `posts` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`slug` text NOT NULL,\n\t`title` text NOT NULL,\n\t`dek` text DEFAULT '' NOT NULL,\n\t`body` text DEFAULT '' NOT NULL,\n\t`category_id` integer,\n\t`author_id` integer,\n\t`cover_key` text,\n\t`cover_alt` text DEFAULT '' NOT NULL,\n\t`status` text DEFAULT 'draft' NOT NULL,\n\t`hero` integer DEFAULT false NOT NULL,\n\t`featured` integer DEFAULT false NOT NULL,\n\t`published_at` integer,\n\t`reads_7d` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,\n\tFOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`author_id`) REFERENCES `editors`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE UNIQUE INDEX `posts_slug` ON `posts` (`slug`);",
      "CREATE INDEX `posts_status_published` ON `posts` (`status`,`published_at`);",
      "CREATE INDEX `posts_category` ON `posts` (`category_id`,`published_at`);"
    ]
  },
  {
    "tag": "0001_settings",
    "statements": [
      "CREATE TABLE `settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch() * 1000) NOT NULL\n);"
    ]
  }
];
